# Generated by Django 5.1.1 on 2024-09-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='placa',
        ),
    ]
